test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -81,7 +81,7 @@ jobs:
           TRAVIS_OS_NAME: "linux"
         run: |
           echo '==================================> SETUP'
-          BOOST_CI_ORG=boostorg BOOST_CI_BRANCH=master && wget https://github.com/$BOOST_CI_ORG/boost-ci/archive/$BOOST_CI_BRANCH.tar.gz && tar -xvf $BOOST_CI_BRANCH.tar.gz && mkdir -p .github &&  mv boost-ci-$BOOST_CI_BRANCH .github/boost-ci
+          # BOOST_CI_ORG=boostorg BOOST_CI_BRANCH=master && wget https://github.com/$BOOST_CI_ORG/boost-ci/archive/$BOOST_CI_BRANCH.tar.gz && tar -xvf $BOOST_CI_BRANCH.tar.gz && mkdir -p .github &&  mv boost-ci-$BOOST_CI_BRANCH .github/boost-ci
           echo '==================================> PACKAGES'
           set -ex
           echo "Before package removal or install"
@@ -96,6 +96,7 @@ jobs:
           ls -al /usr/bin/c*
           echo "about to run sudo apt-get purge -y $PACKAGES_TO_REMOVE"
           if [ -n "$PACKAGES_TO_REMOVE" ]; then sudo apt-get purge -y $PACKAGES_TO_REMOVE; fi
+          ln -s /usr/bin/llvm-cov-9 /usr/bin/llvm-cov
           echo "about to run the equivalent of linux-cxx-install.sh"
 
           set -ex
@@ -181,11 +182,14 @@ jobs:
           ./b2 libs/vmd/test toolset=$TOOLSET
 
           fi
-  osx:
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
+#
+# Github Actions only supports Xcode versions 10.3 and above
+# 
+#   osx:
+#     strategy:
+#       fail-fast: false
+#       matrix:
+#         include:
 #
 # Github Actions only supports Xcode versions 10.3 and above
 # Change (or delete) the Xcode version for this job.
@@ -202,77 +206,80 @@ jobs:
 #             toolset: "clang"
 #             compiler: "clang++"
 #             cxxstd: "c++11"
-
-    runs-on: ${{ matrix.os }}
-
-    steps:
-      - uses: actions/checkout@v2
-
-      - name: Set DEVELOPER_DIR
-        if: matrix.xcode_version != ''
-        run: echo "DEVELOPER_DIR=/Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer" >> $GITHUB_ENV
-      - name: Test DEVELOPER_DIR
-        run: echo $DEVELOPER_DIR
-
-      - name: "osx"
-        shell: bash
-        env:
-          CXX: ${{ matrix.cxx }}
-          SOURCES: ${{ matrix.sources }}
-          LLVM_OS: ${{ matrix.llvm_os }}
-          LLVM_VER: ${{ matrix.llvm_ver }}
-          PACKAGES: ${{ matrix.packages }}
-          JOB_BUILDTYPE: ${{ matrix.buildtype }}
-          TEST_CMAKE: ${{ matrix.test_cmake }}
-          TOOLSET: ${{ matrix.toolset }}
-          COMPILER: ${{ matrix.compiler }}
-          CXXSTD: ${{ matrix.cxxstd }}
-          TRAVIS_BRANCH: ${{ github.base_ref }}
-          TRAVIS_OS_NAME: "osx"
-        run: |
-          echo '==================================> SETUP'
-          set -ex
-          uname -a
-          whoami
-          sudo mv /Library/Developer/CommandLineTools /Library/Developer/CommandLineTools.bck
-          BOOST_CI_ORG=boostorg BOOST_CI_BRANCH=master && /usr/local/bin/wget https://github.com/$BOOST_CI_ORG/boost-ci/archive/$BOOST_CI_BRANCH.tar.gz && tar -xvf $BOOST_CI_BRANCH.tar.gz && mkdir -p .github &&  mv boost-ci-$BOOST_CI_BRANCH .github/boost-ci
-          echo '==================================> PACKAGES'
-          echo "the equivalent of osx-cxx-install.sh would run here."
-
-          echo '==================================> INSTALL AND COMPILE'
-          set -e
-          set -x
-          export TRAVIS_BUILD_DIR=$(pwd)
-          export TRAVIS_BRANCH=${TRAVIS_BRANCH:-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')}
-          export VCS_COMMIT_ID=$GITHUB_SHA
-          export GIT_COMMIT=$GITHUB_SHA
-          export REPO_NAME=$(basename $GITHUB_REPOSITORY)
-          export USER=$(whoami)
-          export CC=${CC:-gcc}
-          export PATH=~/.local/bin:/usr/local/bin:$PATH
-
-          if [ "$JOB_BUILDTYPE" == "boost" ]; then
-
-          echo '==================================> INSTALL'
-
-          cd ..
-          git clone -b $TRAVIS_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
-          cd boost-root
-          git submodule update --init tools/build
-          git submodule update --init libs/config
-          git submodule update --init tools/boostdep
-          git submodule update --init tools/boost_install
-          git submodule update --init libs/headers
-          cp -r $TRAVIS_BUILD_DIR/* libs/vmd
-          python tools/boostdep/depinst/depinst.py vmd
-          ./bootstrap.sh
-          ./b2 headers
-
-          echo '==================================> SCRIPT'
-
-          echo "using $TOOLSET : : $COMPILER : <cxxflags>-std=$CXXSTD ;" > ~/user-config.jam
-          set -e
-          ./b2 libs/preprocessor/test//preprocessor_config toolset=$TOOLSET
-          ./b2 libs/vmd/test toolset=$TOOLSET
-
-          fi
+#
+# Github Actions only supports Xcode versions 10.3 and above
+# 
+# 
+#     runs-on: ${{ matrix.os }}
+# 
+#     steps:
+#       - uses: actions/checkout@v2
+# 
+#       - name: Set DEVELOPER_DIR
+#         if: matrix.xcode_version != ''
+#         run: echo "DEVELOPER_DIR=/Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer" >> $GITHUB_ENV
+#       - name: Test DEVELOPER_DIR
+#         run: echo $DEVELOPER_DIR
+# 
+#       - name: "osx"
+#         shell: bash
+#         env:
+#           CXX: ${{ matrix.cxx }}
+#           SOURCES: ${{ matrix.sources }}
+#           LLVM_OS: ${{ matrix.llvm_os }}
+#           LLVM_VER: ${{ matrix.llvm_ver }}
+#           PACKAGES: ${{ matrix.packages }}
+#           JOB_BUILDTYPE: ${{ matrix.buildtype }}
+#           TEST_CMAKE: ${{ matrix.test_cmake }}
+#           TOOLSET: ${{ matrix.toolset }}
+#           COMPILER: ${{ matrix.compiler }}
+#           CXXSTD: ${{ matrix.cxxstd }}
+#           TRAVIS_BRANCH: ${{ github.base_ref }}
+#           TRAVIS_OS_NAME: "osx"
+#         run: |
+#           echo '==================================> SETUP'
+#           set -ex
+#           uname -a
+#           whoami
+#           sudo mv /Library/Developer/CommandLineTools /Library/Developer/CommandLineTools.bck
+#           # BOOST_CI_ORG=boostorg BOOST_CI_BRANCH=master && /usr/local/bin/wget https://github.com/$BOOST_CI_ORG/boost-ci/archive/$BOOST_CI_BRANCH.tar.gz && tar -xvf $BOOST_CI_BRANCH.tar.gz && mkdir -p .github &&  mv boost-ci-$BOOST_CI_BRANCH .github/boost-ci
+#           echo '==================================> PACKAGES'
+#           echo "the equivalent of osx-cxx-install.sh would run here."
+# 
+#           echo '==================================> INSTALL AND COMPILE'
+#           set -e
+#           set -x
+#           export TRAVIS_BUILD_DIR=$(pwd)
+#           export TRAVIS_BRANCH=${TRAVIS_BRANCH:-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')}
+#           export VCS_COMMIT_ID=$GITHUB_SHA
+#           export GIT_COMMIT=$GITHUB_SHA
+#           export REPO_NAME=$(basename $GITHUB_REPOSITORY)
+#           export USER=$(whoami)
+#           export CC=${CC:-gcc}
+#           export PATH=~/.local/bin:/usr/local/bin:$PATH
+# 
+#           if [ "$JOB_BUILDTYPE" == "boost" ]; then
+# 
+#           echo '==================================> INSTALL'
+# 
+#           cd ..
+#           git clone -b $TRAVIS_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
+#           cd boost-root
+#           git submodule update --init tools/build
+#           git submodule update --init libs/config
+#           git submodule update --init tools/boostdep
+#           git submodule update --init tools/boost_install
+#           git submodule update --init libs/headers
+#           cp -r $TRAVIS_BUILD_DIR/* libs/vmd
+#           python tools/boostdep/depinst/depinst.py vmd
+#           ./bootstrap.sh
+#           ./b2 headers
+# 
+#           echo '==================================> SCRIPT'
+# 
+#           echo "using $TOOLSET : : $COMPILER : <cxxflags>-std=$CXXSTD ;" > ~/user-config.jam
+#           set -e
+#           ./b2 libs/preprocessor/test//preprocessor_config toolset=$TOOLSET
+#           ./b2 libs/vmd/test toolset=$TOOLSET
+# 
+#           fi
